//
// Copyright (c) 2019 Adyen N.V.
//
// This file is open source and available under the MIT license. See the LICENSE file for more info.
//

import Foundation

/// Holds the token generated by the Apple Pay Component.
public struct ApplePayDetails: PaymentMethodDetails {
    
    /// The payment method type.
    public let type: String
    
    /// The token generated by the component.
    public let token: String
    
    /// A string, that describes the payment network backing the card.
    public let network: String
    
    /// Initializes the Apple Pay details.
    ///
    /// :nodoc:
    ///
    /// - Parameters:
    ///   - paymentMethod: The Apple Pay payment method.
    ///   - token: The token generated by the component.
    ///   - network: The payment network backing the Apple pay card.
    public init(paymentMethod: ApplePayPaymentMethod, token: String, network: String) {
        self.type = paymentMethod.type
        self.token = token
        self.network = network
    }
    
    // MARK: - Coding
    
    private enum CodingKeys: String, CodingKey {
        case network = "applePayCardNetwork"
        case token = "applepay.token"
        case type
    }
    
}
