//
// Copyright (c) 2019 Adyen B.V.
//
// This file is open source and available under the MIT license. See the LICENSE file for more info.
//

import Foundation

/// Holds the token generated by the Apple Pay Component.
public struct ApplePayDetails: PaymentMethodDetails {
    
    /// The payment method type.
    public let type: String
    
    /// The token generated by the component.
    public let token: String
    
    // MARK: - Coding
    
    private enum CodingKeys: String, CodingKey {
        case token = "applepay.token"
        case type
    }
    
}
