platform :ios, '9.0'

target 'ShoppingApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Adyen', :path => '../../'
  pod 'Adyen/ApplePay', :path => '../../'

  pod 'SwiftFormat/CLI', '~> 0.28.5'
  pod 'SwiftLint', '~> 0.19.0'
  
  target 'UnitTests' do
    inherit! :search_paths
  end
end
