module: Adyen
author: Adyen
author_url: https://adyen.com
github_url: https://github.com/Adyen/adyen-ios

readme: README.md

output: Docs
theme: fullwidth
skip_undocumented: false
hide_documentation_coverage: true

custom_categories:
  - name: Drop In Component
    children:
      - DropInComponent
      - DropInComponentDelegate
  - name: Card Component
    children:
      - CardComponent
      - CardDetails
      - CardEncryptor
      - CardType
      - CardExpiryDateFormatter
      - CardExpiryDateValidator
      - CardSecurityCodeFormatter
      - CardSecurityCodeValidator
      - CardNumberFormatter
      - CardNumberValidator
      - CardComponentDelegate
      - StoredCardConfiguration
      - CardBrand
  - name: Qiwi Wallet Component
    children:
      - QiwiWalletComponent
      - QiwiWalletDetails
      - QiwiWalletPaymentMethod
  - name: MB Way Component
    children:
      - MBWayComponent
      - MBWayDetails
      - MBWayPaymentMethod
  - name: BLIK Component
    children:
      - BLIKComponent
      - BLIKDetails
      - BLIKPaymentMethod
      - StoredBLIKPaymentMethod
  - name: Await Action Component
    children:
      - AwaitComponent
      - AwaitActionDetails
      - AwaitPaymentMethod
  - name: Doku Component
    children:
      - DokuComponent
      - DokuDetails
      - DokuPaymentMethod
  - name: Voucher Action Component
    children:
      - VoucherComponent
      - VoucherAction
      - VoucherPaymentMethod
  - name: WeChat Pay
    children:
      - WeChatPaySDKActionComponent
      - WeChatPayPaymentMethod
      - WeChatPaySDKAction
      - WeChatPaySDKData
  - name: 3D Secure 2 Component
    children:
      - ThreeDS2Component
      - ThreeDS2ComponentError
      - ThreeDS2Details
  - name: Apple Pay Component
    children:
      - ApplePayComponent
      - ApplePayDetails
  - name: BCMC Component
    children:
      - BCMCComponent
  - name: SEPA Direct Debit Component
    children:
      - SEPADirectDebitComponent
      - SEPADirectDebitDetails
      - IBANFormatter
      - IBANValidator
  - name: Issuer List Component
    children:
      - IssuerListComponent
      - IssuerListDetails
      - IdealComponent
      - IdealDetails
      - MOLPayComponent
      - MOLPayDetails
      - DotpayComponent
      - DotpayDetails
      - EPSComponent
      - EPSDetails
      - EntercashComponent
      - EntercashDetails
      - OpenBankingComponent
      - OpenBankingDetails
  - name: Adyen Action Component
    children:
      - AdyenActionComponent
  - name: Redirect Component
    children:
      - RedirectComponent
      - RedirectDetails
  - name: Base Component
    children:
      - Component
      - PaymentComponent
      - FinalizableComponent
      - PaymentAwareComponent
      - TrackableComponent
      - PaymentComponentData
      - PaymentComponentDelegate
      - PresentationDelegate
      - ActionComponent
      - ActionComponentData
      - ActionComponentDelegate
      - PresentableComponent
      - Details
      - PaymentMethodDetails
      - AdditionalDetails
      - ComponentError
      - SecuredViewController
      - Localizable
  - name: Models
    children:
      - PaymentMethods
      - PaymentMethod
      - StoredPaymentMethod
      - StoredCardPaymentMethod
      - StoredBCMCPaymentMethod
      - StoredPayPalPaymentMethod
      - StoredBLIKPaymentMethod
      - AnyCardPaymentMethod
      - CardPaymentMethod
      - IssuerListPaymentMethod
      - ApplePayPaymentMethod
      - BCMCPaymentMethod
      - SEPADirectDebitPaymentMethod
      - ShopperInteraction
      - DisplayInformation
      - Payment
      - Action
      - RedirectAction
      - GenericVoucherAction
      - ThreeDS2Action
      - SDKAction
      - ThreeDS2FingerprintAction
      - ThreeDS2ChallengeAction
      - AwaitAction
      - CardFundingSource
      - BrowserInfo
      - LocalizationParameters
  - name: Styling
    children:
      - FormComponentStyle
      - FormHeaderStyle
      - FormFooterStyle
      - FormTextItemStyle
      - FormSwitchItemStyle
      - FormButtonItemStyle
      - ListComponentStyle
      - ListSectionHeaderStyle
      - ListItemStyle
      - AwaitComponentStyle
      - RedirectComponentStyle
      - VoucherComponentStyle
      - NavigationStyle
      - ToolbarMode
      - ButtonStyle
      - CancelButtonStyle
      - ImageStyle
      - TextStyle
      - ViewStyle
      - TintableStyle
      - CornerRounding
  - name: Other
    children:
      - AdyenLogging
      - Formatter
      - Validator
      - LengthValidator
      - Environment
      - LogoURLProvider
  - name: Encryption
    children:
      - CardEncryptor
      - Card
      - EncryptedCard
