module: Adyen
author: Adyen
author_url: https://adyen.com
github_url: https://github.com/Adyen/adyen-ios

readme: README.md

output: Docs
theme: fullwidth
skip_undocumented: false
hide_documentation_coverage: true

custom_categories:
  
  - name: Drop In Component
    children:
      - DropInComponent
      - DropInComponentDelegate
      - PaymentMethodListConfiguration
      - StoredPaymentMethodsDelegate
      
  - name: Styling
    children:
      - TextStyle
      - ButtonStyle
      - ImageStyle
      - CornerRounding
      - ToolbarMode
      - FormComponentStyle
      - FormTextItemStyle
      - FormToggleItemStyle
      - FormButtonItemStyle
      - ListComponentStyle
      - ListSectionHeaderStyle
      - ListSectionFooterStyle
      - ListItemStyle
      - ActionComponentStyle
      - AwaitComponentStyle
      - RedirectComponentStyle
      - VoucherComponentStyle
      - QRCodeComponentStyle
      - DocumentComponentStyle
      - NavigationStyle
      - CancelButtonStyle
      - ProgressViewStyle
      - ApplePayStyle

  - name: Basic Payment Methods
    children:
      - PaymentMethod
      - PaymentMethods
      - StoredPaymentMethod
      - IssuerListPaymentMethod
      - AwaitPaymentMethod
      - VoucherPaymentMethod
      - QRCodePaymentMethod
      - DocumentPaymentMethod
      
  - name: Stored payment methods
    children:
      - StoredPayPalPaymentMethod
      - StoredCardPaymentMethod
      - StoredBCMCPaymentMethod
      - StoredBLIKPaymentMethod
      
  - name: Instant payment methods
    children:
      - InstantPaymentMethod
      - MultibancoPaymentMethod
      - OXXOPaymentMethod
      
  - name: Actions
    children:
      - Action
      - RedirectAction
      - ThreeDS2Action
      - ThreeDS2FingerprintAction
      - ThreeDS2ChallengeAction
      - AwaitAction
      - GenericVoucherAction
      - VoucherAction
      - DokuVoucherAction
      - MultibancoVoucherAction
      - BoletoVoucherAction
      - EContextATMVoucherAction
      - EContextStoresVoucherAction
      - OXXOVoucherAction
      - QRCodeAction
      - SDKAction
      - WeChatPaySDKAction
      - DocumentAction
      - AppleWalletError
      
  - name: Action-handling components
    children:
      - AdyenActionComponent
      - VoucherComponent
      - QRCodeComponent
      - AwaitComponent
      - AwaitActionDetails
      - RedirectComponent
      - RedirectDetails
      - WeChatPaySDKActionComponent
      - DocumentComponent
      
  - name: Card Component
    children:
      - AnyCardPaymentMethod
      - CardPaymentMethod
      - BCMCPaymentMethod
      - StoredCardPaymentMethod
      - StoredBCMCPaymentMethod
      - CardComponent
      - BCMCComponent
      - CardDetails
      - KCPDetails
      - CardFundingSource
      - CardType
      - CardBrand
      - CardExpiryDateFormatter
      - CardExpiryDateValidator
      - CardSecurityCodeFormatter
      - CardSecurityCodeValidator
      - CardNumberFormatter
      - CardNumberValidator
      - CardComponentDelegate
      - StoredCardConfiguration
      - InstallmentConfiguration
      - InstallmentOptions
      - Installments
      
  - name: 3D Secure 2 Component
    children:
      - ThreeDS2Component
      - ThreeDS2Details
      - ThreeDS2Action
      - ThreeDS2FingerprintAction
      - ThreeDS2ChallengeAction

  - name: Apple Pay Component
    children:
      - ApplePayPaymentMethod
      - ApplePayComponent
      - ApplePayDetails
      
  - name: Gift Card Component
    children:
      - GiftCardComponent
      - GiftCardDetails
      - GiftCardPaymentMethod
      
  - name: SEPA Direct Debit Component
    children:
      - SEPADirectDebitPaymentMethod
      - SEPADirectDebitComponent
      - SEPADirectDebitDetails
      - IBANFormatter
      - IBANValidator

  - name: BACS Direct Debit Component
    children:
      - BACSDirectDebitPaymentMethod
      - BACSDirectDebitComponent
      - BACSDirectDebitDetails
      
  - name: ACH Direct Debit Component
    children:
      - ACHDirectDebitPaymentMethod
      - ACHDirectDebitComponent
      - ACHDirectDebitDetails

  - name: Qiwi Wallet Component
    children:
      - QiwiWalletPaymentMethod
      - QiwiWalletComponent
      - QiwiWalletDetails
      
  - name: Affirm Component
    children:
      - AffirmPaymentMethod
      - AffirmComponent
      - AffirmDetails
      
  - name: BLIK Component
    children:
      - BLIKPaymentMethod
      - StoredBLIKPaymentMethod
      - BLIKComponent
      - BLIKDetails
            
  - name: Boleto Component
    children:
      - BoletoComponent
      - BoletoPaymentMethod
      - BoletoDetails
      
  - name: MBWay Component
    children:
      - MBWayPaymentMethod
      - MBWayComponent
      - MBWayDetails
      
  - name: WeChat Pay
    children:
      - WeChatPaySDKData
      - WeChatPayPaymentMethod
      - WeChatPaySDKActionComponent
      - WeChatPaySDKAction
      
  - name: Issuer List Component
    children:
      - IssuerListComponent
      - IdealComponent
      - MOLPayComponent
      - DotpayComponent
      - EPSComponent
      - EntercashComponent
      - OpenBankingComponent
      - EntercashDetails
      - OpenBankingDetails
      - EPSDetails
      - DotpayDetails
      - MOLPayDetails
      - IdealDetails
      - IssuerListDetails
      
  - name: EContext Component
    children:
      - EContextPaymentMethod
      - EContextATMComponent
      - EContextOnlineComponent
      - EContextStoreComponent
      - EContextATMVoucherAction
      - EContextStoresVoucherAction
      - SevenElevenPaymentMethod
      - SevenElevenComponent

  - name: Doku Component
    children:
      - VoucherPaymentMethod
      - DokuPaymentMethod
      - DokuComponent
      - DokuDetails
      
  - name: Public Protocols
    children:
      - Component
      - ComponentError
      - PaymentComponent
      - PresentableComponent
      - ActionComponent
      - FinalizableComponent
      - PaymentAwareComponent
      - PartialPaymentError
      - Details
      - AdditionalDetails
      - PaymentMethodDetails
      - AnyVoucherAction

  - name: Public delegates
    children:
      - ActionComponentDelegate
      - PaymentComponentDelegate
      - PresentationDelegate
      - PartialPaymentDelegate
      - StoredPaymentMethodsDelegate
      
  - name: Models
    children:
      - APIContext
      - Payment
      - Amount
      - Balance
      - ShopperName
      - PostalAddress
      - ShopperInteraction
      - DisplayInformation
      - CardFundingSource
      - BrowserInfo
      - ShopperInformation
      - PrefilledShopperInformation
      - PartialPaymentOrder
      - PaymentComponentData
      - ActionComponentData
      
  - name: Encryption
    children:
      - CardEncryptor
      - BankDetailsEncryptor
      - Card
      - EncryptedCard
      - EncryptionError
      
  - name: Utilities
    children:
      - AdyenLogging
      - Formatter
      - Sanitizer
      - BrazilSocialSecurityNumberFormatter
      - threeDS2SdkVersion
      - Validator
      - DateValidator
      - LengthValidator
      - LogoURLProvider
      - SecuredViewController
      - Localizable
      - LocalizationParameters
