module: Adyen
author: Adyen
author_url: https://adyen.com
github_url: https://github.com/Adyen/adyen-ios

readme: README.md

output: Docs
theme: fullwidth
skip_undocumented: false
hide_documentation_coverage: true

custom_categories:
  
  - name: Drop In Component
    children:
      - DropInComponent
      - DropInComponentDelegate
      
  - name: Styling
    children:
      - TextStyle
      - ButtonStyle
      - ImageStyle
      - CornerRounding
      - ToolbarMode
      - FormComponentStyle
      - FormHeaderStyle
      - FormFooterStyle
      - FormTextItemStyle
      - FormToggleItemStyle
      - FormButtonItemStyle
      - ListComponentStyle
      - ListSectionHeaderStyle
      - ListSectionFooterStyle
      - ListItemStyle
      - AwaitComponentStyle
      - RedirectComponentStyle
      - VoucherComponentStyle
      - QRCodeComponentStyle
      - NavigationStyle
      - CancelButtonStyle
      - ProgressViewStyle

  - name: Payment Methods
    children:
      - PaymentMethod
      - PaymentMethods
      - StoredPaymentMethod
      - StoredCardPaymentMethod
      - StoredBCMCPaymentMethod
      - StoredPayPalPaymentMethod
      - StoredBLIKPaymentMethod
      - StoredPayPalPaymentMethod
      - AnyCardPaymentMethod
      - CardPaymentMethod
      - BCMCPaymentMethod
      - IssuerListPaymentMethod
      - ApplePayPaymentMethod
      - SEPADirectDebitPaymentMethod
      - QiwiWalletPaymentMethod
      - AwaitPaymentMethod
      - MBWayPaymentMethod
      - BLIKPaymentMethod
      - VoucherPaymentMethod
      - DokuPaymentMethod
      - EContextPaymentMethod
      - SevenElevenPaymentMethod
      - QRCodePaymentMethod
      - WeChatPayPaymentMethod
      
  - name: Actions
    children:
      - Action
      - RedirectAction
      - ThreeDS2Action
      - ThreeDS2FingerprintAction
      - ThreeDS2ChallengeAction
      - AwaitAction
      - GenericVoucherAction
      - VoucherAction
      - DokuVoucherAction
      - EContextATMVoucherAction
      - EContextStoresVoucherAction
      - QRCodeAction
      - SDKAction
      - WeChatPaySDKAction
      - BoletoVoucherAction
      - DokuVoucherAction
      - EContextATMVoucherAction
      - EContextStoresVoucherAction
      
  - name: Action-handling components
    children:
      - AdyenActionComponent
      - VoucherComponent
      - QRCodeComponent
      - AwaitComponent
      - RedirectComponent
      - WeChatPaySDKActionComponent
      
  - name: Card Component
    children:
      - AnyCardPaymentMethod
      - CardPaymentMethod
      - BCMCPaymentMethod
      - StoredCardPaymentMethod
      - StoredBCMCPaymentMethod
      - CardComponent
      - BCMCComponent
      - CardDetails
      - CardFundingSource
      - CardType
      - CardBrand
      - CardExpiryDateFormatter
      - CardExpiryDateValidator
      - CardSecurityCodeFormatter
      - CardSecurityCodeValidator
      - CardNumberFormatter
      - CardNumberValidator
      - CardComponentDelegate
      - StoredCardConfiguration
      
  - name: 3D Secure 2 Component
    children:
      - ThreeDS2Component
      - ThreeDS2Details
      - ThreeDS2Action
      - ThreeDS2FingerprintAction
      - ThreeDS2ChallengeAction

  - name: Apple Pay Component
    children:
      - ApplePayPaymentMethod
      - ApplePayComponent
      - ApplePayDetails
      
  - name: Gift Card Component
    children:
      - GiftCardComponent
      - GiftCardDetails
      - GiftCardPaymentMethod
      
  - name: SEPA Direct Debit Component
    children:
      - SEPADirectDebitPaymentMethod
      - SEPADirectDebitComponent
      - SEPADirectDebitDetails
      - IBANFormatter
      - IBANValidator
      
  - name: Qiwi Wallet Component
    children:
      - QiwiWalletPaymentMethod
      - QiwiWalletComponent
      - QiwiWalletDetails
      
  - name: BLIK Component
    children:
      - BLIKPaymentMethod
      - StoredBLIKPaymentMethod
      - BLIKComponent
      - BLIKDetails
            
  - name: Boleto Component
    children:
      - BoletoComponent
      - BoletoPaymentMethod
      - BoletoDetails
      
  - name: MBWay Component
    children:
      - MBWayPaymentMethod
      - MBWayComponent
      - MBWayDetails
      
  - name: WeChat Pay
    children:
      - WeChatPaySDKData
      - WeChatPayPaymentMethod
      - WeChatPaySDKActionComponent
      - WeChatPaySDKAction
      
  - name: Issuer List Component
    children:
      - IssuerListComponent
      - IdealComponent
      - MOLPayComponent
      - DotpayComponent
      - EPSComponent
      - EntercashComponent
      - OpenBankingComponent
      - EntercashDetails
      - OpenBankingDetails
      - EPSDetails
      - DotpayDetails
      - MOLPayDetails
      - IdealDetails
      - IssuerListDetails
      
  - name: EContext Component
    children:
      - EContextPaymentMethod
      - EContextATMComponent
      - EContextOnlineComponent
      - EContextStoreComponent
      - EContextATMVoucherAction
      - EContextStoresVoucherAction
      - SevenElevenPaymentMethod
      - SevenElevenComponent

  - name: Doku Component
    children:
      - VoucherPaymentMethod
      - DokuPaymentMethod
      - DokuComponent
      - DokuDetails
      
  - name: Core Component
    children:
      - Component
      - PaymentComponent
      - PresentableComponent
      - ActionComponent
      - FinalizableComponent
      - PaymentAwareComponent
      - PartialPaymentComponent
      - BasicPersonalInfoFormComponent
      
  - name: Public delegates
    children:
      - ActionComponentDelegate
      - PaymentComponentDelegate
      - PresentationDelegate
      - PartialPaymentDelegate
      
  - name: Models
    children:
      - Payment
      - Amount
      - Balance
      - Details
      - PaymentOrder
      - ShopperName
      - PostalAddress
      - PaymentMethodDetails
      - AdditionalDetails
      - ShopperInteraction
      - DisplayInformation
      - PaymentComponentData
      - CardFundingSource
      - BrowserInfo
      - ShopperInformation
      - PrefilledShopperInformation
      - PartialPaymentOrder
      - LocalizationParameters
      - ActionComponentData
      
  - name: Errors
    children:
      - ComponentError
      - PartialPaymentError
      - ThreeDS2ComponentError
      
  - name: Encryption
    children:
      - CardEncryptor
      - Card
      - EncryptedCard
      
  - name: API Reference
    children:
      - Payment
      - PaymentComponentData
      - PaymentMethod
      - PaymentMethods
      - StoredPaymentMethod
      - ShopperInteraction
      - ShopperInformation
      - DisplayInformation
      - BillingAddressInformation
      - CardFundingSource
      - BrowserInfo
      - AddressInfo
      - ShopperName
      - Details
      - PaymentMethodDetails
      - RedirectDetails
      - AdditionalDetails
      - AwaitActionDetails
      
  - name: Utilities
    children:
      - AdyenLogging
      - Formatter
      - Validator
      - LengthValidator
      - Environment
      - LogoURLProvider
      - SecuredViewController
      - Localizable
      - LocalizationParameters
