module: Adyen
author: Adyen
author_url: https://adyen.com
github_url: https://github.com/Adyen/adyen-ios

readme: README.md

output: Docs

theme: Docs/theme
skip_undocumented: false
hide_documentation_coverage: true

custom_categories:
  - name: UI
    children:
    - CheckoutController
    - CheckoutControllerDelegate
  - name: Appearance
    children:
    - Appearance
  - name: Redirect
    children:
    - applicationDidOpen(_:)
  - name: Payment
    children:
    - PaymentController
    - PaymentControllerDelegate
    - PaymentSession
    - PaymentResult
  - name: Payment Method
    children:
    - SectionedPaymentMethods
    - PaymentMethod
    - PaymentDetail
    - AdditionalPaymentDetails
    - IdentificationPaymentDetails
    - ChallengePaymentDetails
    - StoredPaymentDetails
    - StoredCardPaymentDetails
    - StoredPayPalPaymentDetails
  - name: Other
    children:
    - Completion
    - Result
    - Array
  - name: Card Module
    children:
    - Card3DS2Authenticator
    - CardEncryptor
    - CardScanDelegate
    - CardScanCompletion
