module: Adyen
author: Adyen
author_url: https://adyen.com
github_url: https://github.com/Adyen/adyen-ios

readme: README.md

output: Docs
theme: fullwidth
skip_undocumented: false
hide_documentation_coverage: true

custom_categories:
  - name: Drop In Component
    children:
      - DropInComponent
      - DropInComponentDelegate
  - name: Card Component
    children:
      - CardComponent
      - CardDetails
      - CardEncryptor
      - CardType
      - CardTypeDetector
      - CardExpiryDateFormatter
      - CardExpiryDateValidator
      - CardSecurityCodeFormatter
      - CardSecurityCodeValidator
      - CardNumberFormatter
      - CardNumberValidator
  - name: 3D Secure 2 Component
    children:
      - ThreeDS2Component
      - ThreeDS2Details
  - name: SEPA Direct Debit Component
    children:
      - SEPADirectDebitComponent
      - SEPADirectDebitDetails
      - IBANFormatter
      - IBANValidator
  - name: Issuer List Component
    children:
      - IssuerListComponent
      - IssuerListDetails
      - IdealComponent
      - IdealDetails
      - MOLPayComponent
      - MOLPayDetails
      - DotpayComponent
      - DotpayDetails
      - EPSComponent
      - EPSDetails
      - EntercashComponent
      - EntercashDetails
      - OpenBankingComponent
      - OpenBankingDetails
  - name: Redirect Component
    children:
      - RedirectComponent
      - RedirectDetails
  - name: Base Component
    children:
      - Component
      - PaymentComponent
      - PaymentComponentData
      - PaymentComponentDelegate
      - ActionComponent
      - ActionComponentData
      - ActionComponentDelegate
      - PresentableComponent
      - Details
      - PaymentMethodDetails
      - AdditionalDetails
      - ComponentError
  - name: Models
    children:
      - PaymentMethods
      - PaymentMethod
      - StoredPaymentMethod
      - StoredCardPaymentMethod
      - StoredPayPalPaymentMethod
      - CardPaymentMethod
      - IssuerListPaymentMethod
      - SEPADirectDebitPaymentMethod
      - ShopperInteraction
      - Payment
      - Action
      - RedirectAction
      - ThreeDS2FingerprintAction
      - ThreeDS2ChallengeAction
  - name: Other
    children:
      - Formatter
      - Validator
      - LengthValidator
      - Environment
      - LogoURLProvider
