version: 1
builder:
  configs:
    - documentation_targets:
        - Adyen
        - AdyenActions
        - AdyenCard
        - AdyenComponents
        - AdyenSession
        - AdyenDropIn
        - AdyenEncryption
        - AdyenWeChatPay
        - AdyenCashAppPay
        - AdyenSwiftUI
        - AdyenTwint
      platform: [ios]
      swift_version: 5.7