version: 1
builder:
  configs:
    - documentation_targets: [Adyen, AdyenActions, AdyenCard, AdyenComponents, AdyenSession, AdyenDropIn, AdyenEncryption, AdyenWeChatPay, AdyenCashAppPay, AdyenTwint]
      platform: ios
