disabled_rules:
  - trailing_whitespace
  - nesting
  - todo

opt_in_rules:
  - explicit_acl

excluded:
  - AdyenTests
  - AdyenUITests
  - Examples
  - Internal

line_length:
  ignores_function_declarations: true
  ignores_urls: true
  warning: 140
