disabled_rules:
  - cyclomatic_complexity
  - line_length
  - trailing_whitespace
  - operator_whitespace
  - unused_closure_parameter
  - todo
  - fallthrough
  - identifier_name

  #Review:
  - large_tuple
  - function_body_length
  - file_length
included:
  - Adyen
  - AdyenTests
  - AdyenUITests
  - AdyenUIHost
excluded:
  - Pods
