language: objective-c

osx_image: xcode9.3

env:
  global:
    - WORKSPACE="Adyen.xcworkspace"
    - SCHEME="AdyenUIHost"
    - DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=11.3"

before_install:
  - gem install cocoapods
  - pod repo update
  - pod install

script:
  - ./Pods/SwiftLint/swiftlint
  - xcodebuild test -workspace "${WORKSPACE}" -scheme "${SCHEME}" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination "${DESTINATION}" |  xcpretty -s && exit ${PIPESTATUS[0]}
