//
// Copyright (c) 2026 Adyen N.V.
//
// This file is open source and available under the MIT license. See the LICENSE file for more info.
//

import Foundation

extension CurrencyMinorDigitsProvider {

    /// Currency minor digits according to Adyen.
    /// Source: https://docs.adyen.com/development-resources/currency-codes
    ///
    /// A small number of additional ISO 4217 codes that are not on Adyen's official currency
    /// list are also included below (marked accordingly), since this provider is currency-agnostic
    /// and may be called with codes outside of Adyen's supported payment currencies.
    internal static let minorDigitsByCurrencyCode: [String: Int] = [
        "ADP": 0, // Not an Adyen currency. Historical (Andorran Peseta, obsolete since 1999).
        "AED": 2,
        "ALL": 2,
        "AMD": 2,
        "AOA": 2,
        "ARS": 2,
        "AUD": 2,
        "AWG": 2,
        "AZN": 2,
        "BAM": 2,
        "BBD": 2,
        "BDT": 2,
        "BHD": 3,
        "BIF": 0, // Not an Adyen currency. Active national currency (Burundian Franc).
        "BMD": 2,
        "BND": 2,
        "BOB": 2,
        "BRL": 2,
        "BSD": 2,
        "BWP": 2,
        "BYN": 2,
        "BYR": 0, // Not an Adyen currency. Historical (Belarusian Ruble, obsolete since 2016).
        "BZD": 2,
        "CAD": 2,
        "CHF": 2,
        "CLF": 4, // Not an Adyen currency. Chilean Unidad de Fomento (indexed accounting unit).
        "CLP": 2,
        "CNH": 2,
        "CNY": 2,
        "COP": 2,
        "CRC": 2,
        "CUP": 2,
        "CVE": 0,
        "CZK": 2,
        "DJF": 0,
        "DKK": 2,
        "DOP": 2,
        "DZD": 2,
        "EGP": 2,
        "ESP": 0, // Not an Adyen currency. Historical (Spanish Peseta, obsolete since 1999).
        "ETB": 2,
        "EUR": 2,
        "FJD": 2,
        "FKP": 2,
        "GBP": 2,
        "GEL": 2,
        "GHS": 2,
        "GIP": 2,
        "GMD": 2,
        "GNF": 0,
        "GTQ": 2,
        "GYD": 2,
        "HKD": 2,
        "HNL": 2,
        "HTG": 2,
        "HUF": 2,
        "IDR": 0,
        "ILS": 2,
        "INR": 2,
        "IQD": 3,
        "ISK": 2,
        "ITL": 0, // Not an Adyen currency. Historical (Italian Lira, obsolete since 1999).
        "JMD": 2,
        "JOD": 3,
        "JPY": 0,
        "KES": 2,
        "KGS": 2,
        "KHR": 2,
        "KMF": 0,
        "KRW": 0,
        "KWD": 3,
        "KYD": 2,
        "KZT": 2,
        "LAK": 2,
        "LKR": 2,
        "LYD": 3,
        "MAD": 2,
        "MDL": 2,
        "MGF": 0, // Not an Adyen currency. Historical (Malagasy Franc, obsolete since 2005).
        "MKD": 2,
        "MMK": 2,
        "MNT": 2,
        "MOP": 2,
        "MRU": 2,
        "MUR": 2,
        "MVR": 2,
        "MWK": 2,
        "MXN": 2,
        "MYR": 2,
        "MZN": 2,
        "NAD": 2,
        "NGN": 2,
        "NIO": 2,
        "NOK": 2,
        "NPR": 2,
        "NZD": 2,
        "OMR": 3,
        "PAB": 2,
        "PEN": 2,
        "PGK": 2,
        "PHP": 2,
        "PKR": 2,
        "PLN": 2,
        "PYG": 0,
        "QAR": 2,
        "RON": 2,
        "RSD": 2,
        "RUB": 2,
        "RWF": 0,
        "SAR": 2,
        "SBD": 2,
        "SCR": 2,
        "SEK": 2,
        "SGD": 2,
        "SHP": 2,
        "SLE": 2,
        "SOS": 2,
        "SRD": 2,
        "STN": 2,
        "SVC": 2,
        "SZL": 2,
        "THB": 2,
        "TND": 3,
        "TOP": 2,
        "TRL": 0, // Not an Adyen currency. Historical (Turkish Lira, obsolete since 2005).
        "TRY": 2,
        "TTD": 2,
        "TWD": 2,
        "TZS": 2,
        "UAH": 2,
        "UGX": 0,
        "USD": 2,
        "UYI": 0, // Not an Adyen currency. Uruguay Peso en Unidades Indexadas (indexed accounting unit).
        "UYU": 2,
        "UYW": 4, // Not an Adyen currency. Uruguay Unidad Previsional (indexed accounting unit).
        "UZS": 2,
        "VND": 0,
        "VUV": 0,
        "WST": 2,
        "XAF": 0,
        "XCD": 2,
        "XCG": 2,
        "XOF": 0,
        "XPF": 0,
        "YER": 2,
        "ZAR": 2,
        "ZMW": 2
    ]
}
