#!/usr/bin/env xcrun swift

import Foundation

let header =
"""
//
// Copyright (c) 2021 Adyen N.V.
//
// This file is open source and available under the MIT license. See the LICENSE file for more info.
// This file is autogenerated. Please do not modify it.


"""

let structName = "ADYLocalizationKey"

func extractKey(_ line: String) -> String {
    String(line.prefix(while: { $0 != " " }))
        .trimmingCharacters(in: CharacterSet(charactersIn: "\""))
}

func capitalizeFirstLetter(_ string: String) -> String {
    string.prefix(1).capitalized + string.dropFirst()
}

func formatKeyToName(_ key: String) -> String {
    let comps = key.components(separatedBy: ".")
        .dropFirst()
    return Array(comps.prefix(1) + comps.dropFirst().map(capitalizeFirstLetter(_:)))
        .joined()
}

func generate(_ name: String, _ key: String) -> String {
    String(format: "public static let %@ = %@(key: \"%@\")", name, structName, key)
}

func generateStruct(
    _ lines: Array<String>,
    indent: String = "\n    ") -> String {
    "/// :nodoc:\npublic struct \(structName) {\n\(indent)\(lines.joined(separator: indent))\n\(indent)internal let key: String\n\n}"
}

let inputPath = CommandLine.arguments[1]
let outputPath = CommandLine.arguments[2]
let fm = FileManager.default
let cwd = fm.currentDirectoryPath
let inputURL = URL(fileURLWithPath: inputPath, relativeTo: URL(fileURLWithPath: cwd, isDirectory: true))

guard let fileContents = FileManager.default.contents(atPath: inputURL.relativePath),
      let strings = String(data: fileContents, encoding: .utf8) else {
    fatalError("Error reading input file at \(inputURL.relativePath)")
}

let lines = strings.components(separatedBy: .newlines)
    .filter { $0.isEmpty == false }
    .map(extractKey)
    .map { (formatKeyToName($0), $0) }
    .map(generate)

print("Detected \(lines.count) localizable keys")

let finalStruct = generateStruct(lines)
let finalResult = header.appending(finalStruct)

guard let data = finalResult.data(using: .utf8) else {
    print("Error creating writeable from generated string")
    fatalError()
}

let outputURL = URL(
    fileURLWithPath: outputPath,
    relativeTo: URL(fileURLWithPath: cwd, isDirectory: true))

if fm.fileExists(atPath: outputURL.relativePath) {
    print("Output file already exists at \(outputURL.absoluteString). Replacing the contents")
    do {
        try data.write(to: outputURL)
    } catch (let error) {
        print("File writing to \(outputURL.relativePath) failed with \(error)")
    }
} else {
    print("Output file does not exist at \(outputURL.absoluteString). Proceeding with creation...")
    if fm.createFile(atPath: outputURL.relativePath, contents: data, attributes: nil) {
        print("Output file successfuly created")
    } else {
        print("Output file creation failed")
    }
}
