# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Advanced' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Advanced
  pod 'Adyen/Core', :path => '../../'
  pod 'Adyen/Cards', :path => '../../'

end
