platform :ios, '10.3'

use_frameworks!

target 'Quick Integration Example' do

  pod 'Adyen', :path => '../../'
  pod 'Adyen/ApplePay', :path => '../../'
  pod 'Adyen/Card3DS2', :path => '../../'
  pod 'AdyenInternal', :path => '../../'

end
