name: Base Environment Workflow

on:
  workflow_call:

env:
  XCODE_VERSION: '16.1'  # Define the Xcode version here

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - name: Print Xcode version
        run: echo "The selected Xcode version is $XCODE_VERSION"
