# .github/workflows/cancel-duplicate-work-flows.yml
name: Cancel duplicate work flows

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  cancel-multiple-workflow-runs:
    name: "Cancel the self CI workflow run"
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: "Cancel build"
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          workflow_id: build.yml
          access_token: ${{ secrets.GITHUB_TOKEN }}
          all_but_latest: true

      - name: "Cancel pr scan"
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          workflow_id: pr_scan.yml
          access_token: ${{ secrets.GITHUB_TOKEN }}
          all_but_latest: true

      - name: "Cancel spell check"
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          workflow_id: spell-check.yml
          access_token: ${{ secrets.GITHUB_TOKEN }}
          all_but_latest: true

      - name: "Cancel test_cocoapods_integration"
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          workflow_id: test_cocoapods_integration.yml
          access_token: ${{ secrets.GITHUB_TOKEN }}
          all_but_latest: true

      - name: "Cancel test-SPM-integration"
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          workflow_id: test-SPM-integration.yml
          access_token: ${{ secrets.GITHUB_TOKEN }}
          all_but_latest: true

      - name: "Cancel validate_pr_labels_and_release_notes"
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          workflow_id: validate_pr_labels_and_release_notes.yml
          access_token: ${{ secrets.GITHUB_TOKEN }}
          all_but_latest: true
