name: "🚀 Release on merge"

on:
  pull_request:
    types: [closed]

jobs:
  create_release:
    if: github.event.pull_request.merged == true
    name: "Create Release"
    runs-on: ubuntu-latest
    
    steps:
    # Checking out the current branch
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Getting the description for the pull request that was merged
    - name: Fetch Pull Request Details
      run: |
        SOURCE_BRANCH=$(jq --raw-output .pull_request.head.ref "$GITHUB_EVENT_PATH")
        if [[ "$SOURCE_BRANCH" != release/* ]]; then
          echo "Source branch does not match pattern. Exiting."
          exit 1
        fi
        
        VERSION_NUMBER=${SOURCE_BRANCH#release/}
        if [[ ! "$VERSION_NUMBER" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "SUFFIX does not match semantic versioning format. Exiting."
          exit 1
        fi
        
        echo "SOURCE_BRANCH=$SOURCE_BRANCH" >> $GITHUB_ENV
        echo "VERSION_NUMBER=$VERSION_NUMBER" >> $GITHUB_ENV
        
        MERGE_COMMIT_SHA=$(jq --raw-output .pull_request.merge_commit_sha "$GITHUB_EVENT_PATH")
        echo "MERGE_COMMIT_SHA=$MERGE_COMMIT_SHA" >> $GITHUB_ENV
        
        PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        echo "PR Number: $PR_NUMBER"
        
        CURL_OUTPUT=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER})
        echo "CURL Output: $CURL_OUTPUT"
        
        PR_DESCRIPTION=$(jq --raw-output .body <<< "$CURL_OUTPUT")
        echo "PR Description: $PR_DESCRIPTION"
        
        echo "$PR_DESCRIPTION" >> "${{ github.workspace }}/release_body.md"
        
    - name: Drafting Release
      uses: softprops/action-gh-release@v2
      with:
        body_path: "${{ github.workspace }}/release_body.md"
        draft: true
        target_commitish: ${{ env.MERGE_COMMIT_SHA }}
        tag_name: ${{ env.VERSION_NUMBER }}
        token: ${{ secrets.GITHUB_TOKEN }}
