name: Pull Request Merge

on:
  pull_request:
    types: [closed]
    branches:
      - 'release/*'

jobs:
  create_release:
    if: github.event.pull_request.merged == true
    name: "Create Release"
    runs-on: ubuntu-latest
    
    steps:
    # Checking out the current branch
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Getting the description for the pull request that was merged
    - name: Fetch Pull Request Description
      run: |
        PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        PR_DESCRIPTION=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER} | jq --raw-output .body)
        echo "PR_DESCRIPTION=$PR_DESCRIPTION" >> $GITHUB_ENV

    - name: Create Release
      run: |
        echo "Creating Release for Version: ???"
        echo "Description: ${{ env.PR_DESCRIPTION }}"
