name: 📝 Deploy Docs
on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pages: write 

jobs:

  Deploy:
    runs-on: macos-26-xlarge
    steps:
    - uses: actions/checkout@v7

    - name: Select latest Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Set current marketing version
      run: echo "MARKETING_VERSION=$(agvtool what-marketing-version -terse1)" >> $GITHUB_OUTPUT
      id: get-current-marketing-version

    - name: Generate Docs
      run: Scripts/generate_docc_documentation.sh
      env:
        LATEST_VERSION: ${{ steps.get-current-marketing-version.outputs.MARKETING_VERSION }}

    - name: Deploy to current version 🚀
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html
        destination_dir: ./${{ steps.get-current-marketing-version.outputs.MARKETING_VERSION }}
        
    - name: Deploy to root 🚀
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/redirect
        keep_files: true
