name: Firebase Distribution

# on:
#   workflow_dispatch:
#     inputs:
#       branch:
#         description: "Branch to build and distribute"
#         required: true
#         default: "develop"

on:
  pull_request:
    branches:
      - develop

permissions:
  contents: read

jobs:
  distribute:
    runs-on: macos-15-xlarge

    steps:
      - name: 🪾 Checkout selected branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: 🛠️ Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash

      - name: 📝 Determine release name
        id: release_name
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          SHORT_SHA=$(git rev-parse --short HEAD)
          RELEASE_NAME="firebase-${BRANCH_NAME}-${SHORT_SHA}"
          echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV
          echo "Release name set to $RELEASE_NAME"

      - name: 🚀 Distribute to Firebase
        env:
          # Workflow configuration
          APPLE_ID_USERNAME: ${{ secrets.APPLE_ID_USERNAME }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          XCODE_AUTHENTICATION_KEY_ID: ${{ secrets.XCODE_AUTHENTICATION_KEY_ID }}
          XCODE_AUTHENTICATION_KEY_ISSUER_ID: ${{ secrets.XCODE_AUTHENTICATION_KEY_ISSUER_ID }}
          XCODE_AUTHENTICATION_KEY_BASE64: ${{ secrets.XCODE_AUTHENTICATION_KEY_BASE64 }}

          # Firebase env
          FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_RELEASE_NAME: ${{ env.RELEASE_NAME }}
          
          # App build configuration
          MERCHANT_CLIENT_KEY: ${{ secrets.DEMO_APP_TEST_ENV_CLIENT_KEY }}
          MERCHANT_SERVER_HOST: ${{ secrets.MERCHANT_SERVER_HOST }}
          MERCHANT_ACCOUNT: ${{ secrets.MERCHANT_ACCOUNT }}
          ADYEN_SERVER_API_KEY: ${{ secrets.DEMO_SERVER_TEST_ENV_API_KEY }}
          APPLE_TEAM_IDENTIFIER: ${{ secrets.APPLE_DEVELOPMENT_TEAM_ID }}
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
        run: |
          AUTH_KEY_PATH=$RUNNER_TEMP/authentication_key_path.p8
          rm -f $AUTH_KEY_PATH
          echo -n "$XCODE_AUTHENTICATION_KEY_BASE64" | base64 --decode -o $AUTH_KEY_PATH

          # Make it available for the current shell
          export AUTH_KEY_PATH=$AUTH_KEY_PATH

          chmod +x ./Scripts/publish-demo-app.sh
          ./Scripts/publish-demo-app.sh "firebsae"
