name: Firebase Distribution

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build and distribute"
        required: true
        default: "develop"

permissions:
  contents: read

jobs:
  distribute:
    runs-on: macos-15-xlarge

    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash

      - name: Set environment variables
        run: |
          echo "CLIENT_KEY=${{ secrets.CLIENT_KEY }}" >> $GITHUB_ENV
          echo "DEMO_SERVER_API_KEY=${{ secrets.DEMO_SERVER_API_KEY }}" >> $GITHUB_ENV
          echo "MERCHANT_ACCOUNT=${{ secrets.MERCHANT_ACCOUNT }}" >> $GITHUB_ENV
          echo "APPLE_DEVELOPMENT_TEAM_ID=${{ secrets.APPLE_DEVELOPMENT_TEAM_ID }}" >> $GITHUB_ENV
          echo "ENVIRONMENT=ci" >> $GITHUB_ENV
          echo "FIREBASE_SERVICE_ACCOUNT_JSON=${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}" >> $GITHUB_ENV
          echo "FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" >> $GITHUB_ENV
          echo "XCODE_AUTHENTICATION_KEY_ID=${{ secrets.XCODE_AUTHENTICATION_KEY_ID }}" >> $GITHUB_ENV
          echo "XCODE_AUTHENTICATION_KEY_ISSUER_ID=${{ secrets.XCODE_AUTHENTICATION_KEY_ISSUER_ID }}" >> $GITHUB_ENV

      - name: Determine release name
        id: release_name
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          SHORT_SHA=$(git rev-parse --short HEAD)
          RELEASE_NAME="firebase-${BRANCH_NAME}-${SHORT_SHA}"
          echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV
          echo "Release name set to $RELEASE_NAME"

      - name: Run Firebase distribution script
        run: |
          chmod +x scripts/publish-demo-app.sh
          ./Scripts/publish-demo-app.sh \
            "${{ secrets.APPLE_ID_USERNAME }}" \
            "${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}" \
            "${{ secrets.XCODE_AUTHENTICATION_KEY_PATH }}" \
            "firebase"
        env:
          FIREBASE_RELEASE_NAME: ${{ env.RELEASE_NAME }}
