name: Generate Docs
on: 
  workflow_dispatch:
    inputs:
      latestVersion:
        description: 'Whats the latest version of the SDK?'
        required: true
        
  workflow_call:
    inputs:
      latestVersion:
        description: 'SDK Version for the Release'
        required: true
        type: string
        
jobs:

  Generate:
    runs-on: macos-14
    steps:
    - name: 🍱 Compute prerequisites
      run: |
        echo "BASE_REPO=${{ github.repository }}" >> $GITHUB_ENV
        echo "BASE_REF=${{ env.target }}" >> $GITHUB_ENV
        echo "HEAD_REF=${{ env.base }}" >> $GITHUB_ENV
      shell: bash
      env:
        target: '${{ github.event.pull_request.base.ref }}'
        base: '${{ github.head_ref }}'
    
    - uses: actions/checkout@v4
      with:
        repository: ${{ env.BASE_REPO }}
        ref: ${{ env.HEAD_REF }}
        
    - uses: n1hility/cancel-previous-runs@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Select latest Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Generate Docs
      run: |
        Scripts/generate_docc_documentation.sh
      env:
        LATEST_VERSION: ${{ github.event.inputs.latestVersion }}
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        delete-branch: true
        branch: "update-docs-github-action-${{ env.HEAD_REF }}"
        commit-message: "chore: updating documentation"
        title: "[${{ env.HEAD_REF }}] Update documentation"
        body: "Updated documentation for `${{ env.HEAD_REF }}`"
        token: ${{ secrets.GITHUB_TOKEN }}
