name: Generate Docs
on: 
  workflow_dispatch:
    inputs:
      latestVersion:
        description: 'Whats the latest version of the SDK?'
        required: true
jobs:

  Generate:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: n1hility/cancel-previous-runs@v2
      with:
        token: ${{ secrets.MANUAL_ACTION_TOKEN }}

    - name: Select latest Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Generate Docs
      run: |
        Scripts/generate_docc_documentation.sh
      env:
        LATEST_VERSION: ${{ github.event.inputs.latestVersion }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        delete-branch: true
        branch: update-docs-github-action
        commit-message: "chore: updated documentation"
        title: update documentation
        body: Regenerate documentation.
        token: ${{ secrets.MANUAL_ACTION_TOKEN }}
