name: Generate Docs
on: [workflow_dispatch]
jobs:

  Generate:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: n1hility/cancel-previous-runs@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Select latest Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Generate Docs
      run: |
        gem install cocoapods
        gem install jazzy
        Scripts/generate_documentation.sh
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        delete-branch: true
        branch: update-docs-github-action
        commit-message: "chore: updated documentation"
        title: update documentation
        body: Regenerate documentation.
        token: ${{ secrets.GITHUB_TOKEN }}
