name: 📸 Generate Snapshots
on:
    workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read          
jobs:
  Generate:
    runs-on: macos-26-xlarge
    
    steps:
    - uses: actions/checkout@v6

    - name: 🔨 Select Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '26.2'

    - name: 🧹 Clear existing Snapshots
      run: |
        find ./Tests/SnapshotTests -name "__Snapshots__" -exec rm -rf {} +
    - name: 📸 Generate Snapshots
      run: |
        xcodebuild test -project "${project}" -scheme "${scheme}" ${params} -destination "platform=iOS Simulator,name=iPhone 16,OS=26.2" -destination "platform=iOS Simulator,name=iPad (10th generation),OS=26.2" | xcpretty --utf --color
      env:
        project: 'Adyen.xcodeproj'
        params: '-skipPackagePluginValidation'
        scheme: 'GenerateSnapshots'
        
    - name: 🚀 Create Pull Request
      uses: peter-evans/create-pull-request@v8
      with:
        delete-branch: true
        branch: chore/update-snapshots-github-action
        commit-message: "🤖 Generated Snapshots"
        title: "🤖 Generate Snapshots"
        body: "Regenerate snapshots"
        token: ${{ secrets.AUTOMATION_BOT_TOKEN }}
