# .github/workflows/sdk-size-analysis.yml
name: SDK Size Analysis

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  analyze-sdk-size:
    runs-on: macos-15-xlarge

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.1'

      - name: Run SDK Size Analysis Script
        run: |
          ./Scripts/sdk_size_analysis.sh

      - name: Upload framework sizes JSON artifact
        uses: actions/upload-artifact
        with:
          name: sdk-sizes-${{ github.head_ref }}
          path: sdk_size_output/sdk_sizes.json
