name: Base Xcode Setup

on:
  workflow_call:

jobs:
  setup-xcode:
    runs-on: macos-latest
    steps:
      - name: Select Xcode 16.1
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.1'