name: Spell check

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  setup:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: Spell check
      run: |
        brew install mint
        Scripts/spell_check.sh
      env:
        target_branch: ${{ github.event.pull_request.base.ref }}
