name: Test Swift Package Manager Integration

on:
  pull_request:
    types: [opened, synchronize, reopened]

  push:
    branches:
    - master
    - develop

jobs:

  SPM:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Select latest Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Test Swift Package Manager Integration
      run: |
        Scripts/test-SPM-integration.sh
