name: Test Swift Package Manager Integration

on:
  pull_request:
    types: [opened, synchronize, reopened]

  push:
    branches:
    - master
    - develop

jobs:

  SPM:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Xcode 12.2
      run: |
        echo '::set-output name=XCODE_VERSION::/Applications/Xcode_12.2.app/Contents/Developer'
        xcodebuild -version

    - name: Test Swift Package Manager Integration
      run: |
        ./test-SPM-integration.sh
