name: 📚 Library Evolution Compatibility

on:
#  pull_request:
#    types: [opened, synchronize, reopened]
    
  push:
    branches:
      - develop
      
jobs:

  build:
    name: Verify
    runs-on: macos-13-xl

    steps:
    - uses: actions/checkout@v4
    - uses: n1hility/cancel-previous-runs@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Select latest Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.3'

    - name: "xcodebuild clean archive BUILD_LIBRARY_FOR_DISTRIBUTION=YES"
      run: |
        xcodebuild -version
        xcodebuild clean archive -project "${project}" -scheme "${scheme}" ${params} -destination "${destination}" | xcpretty --utf --color && exit ${PIPESTATUS[0]}
      env:
        project: 'Adyen.xcodeproj'
        params: '-archivePath "archives/Adyen-iphoneos.xcarchive" -skipPackagePluginValidation SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES'
        scheme: 'Adyen'
        destination: 'generic/platform=iOS'
