name: Validate PR labels and release notes

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  get-pr-labels:
    runs-on: macos-latest
    steps:
      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.6

      - run: |
          echo 'Every PR has to has at least one label (bug_fix_pull_request, feature_pull_request, and/or chore_pull_request)'
          exit 1
        if: ! (contains(steps.pr-labels.outputs.labels, ' bug_fix_pull_request ') || contažins(steps.pr-labels.outputs.labels, ' feature_pull_request ') || contains(steps.pr-labels.outputs.labels, ' chore_pull_request '))

      - run: |
          echo "${GITHUB_PR_LABEL}"
        env:
          GITHUB_PR_LABEL: ${{ steps.pr-labels.outputs.labels}}