name: 🎫 Validate ticket reference

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  branches:
    - develop
  paths-ignore:
    - 'release/*'
jobs:
  validate-ticket:
    runs-on: ubuntu-latest
    steps:
      - name: Check ticket reference
      - env:
        PR_BODY: ${{github.event.pull_request.body}}
        TICKET_REGEX: '<ticket>COIOS-[0-9]+</ticket>'
      - run: |
          if ! grep -qE "$TICKET_REGEX" <<< "$PR_BODY"; then
            echo "::error::Pull requests must have a ticket number in the pull request body in the format '<ticket>COIOS-XXX</ticket>' where XXX is a numeric ticket number"
            exit 1
          fi
