name: Validate PR labels and release notes

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  get-pr-labels:
    runs-on: macos-latest
    steps:
      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.6

      - run: |
          echo '${{ steps.pr-labels.outputs.labels}}'

      - run: |
          if [[ '${{steps.pr-labels.outputs.labels}}' != *' bug-fix-pull-request '* && '${{steps.pr-labels.outputs.labels}}' != *' feature-pull-request '* &&  '${{steps.pr-labels.outputs.labels}}' != *' chore-pull-request '* ]]; then
             echo 'Every PR has to has at least one label (bug_fix_pull_request, feature_pull_request, and/or chore_pull_request)'
             exit 1
          fi
      - run: |
          echo '${{ steps.pr-labels.outputs.labels}}'