name: Validate PR labels and release notes

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled, edited]

jobs:
  get-pr-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get the list of allowed pull request labels
        run: |
          FILE_NAME=.pull-requests-allowed-labels-list
          FILE_PATH=$PROJECT_ROOT/$FILE_NAME
          if [[ ! -f "$FILE_PATH" ]]; then
             echo "$FILE_NAME file doesn't exits in the root of the respository"
             exit 1
          fi 
          echo "::set-output name=LABELS::$(cat $FILE_PATH)"
        id: get-allowed_labels
        env:
          PROJECT_ROOT: ${{ github.workspace }}

      - name: Validate labels
        uses: jesusvasquez333/verify-pr-label-action@v1.4.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          valid-labels: ${{ steps.get-allowed_labels.outputs.LABELS }}

      - name: Get PR labels
        uses: joerick/pr-labels-action@v1.0.6
        id: pr-labels

      - name: Get PR body
        uses: technote-space/pr-commit-body-action@v1

      - run: |
          IFS=',' read -r -a ALLOWED_LABELS_ARRAY <<< "$ALLOWED_LABELS"

          for LABEL in "${ALLOWED_LABELS_ARRAY[@]}"; do
            LABEL=$(echo "$LABEL" | sed 's/^ *//g' | sed 's/^ *//g')
            echo "$LABEL"
            if [[ "$LABEL" == "chore" ]]; then
              continue
            fi
            if [[ "$PR_LABELS" == *"$LABEL"* ]]; then
              cmd="awk '/$LABEL:\s*<.*>/'"
              FEATURE_RELEASE_NOTE="$(echo $PR_BODY | eval $cmd)"
              if [[ -z "$FEATURE_RELEASE_NOTE" ]]; then
                 echo "Pull requests labeled with '$LABEL' must have the release note in the pull request body in the following format '$LABEL: < {THE RELEASE NOTE} >'"
                 exit 1
              fi
            fi
          done
        env:
          PR_BODY: ${{github.event.pull_request.body}}
          PR_LABELS: ${{steps.pr-labels.outputs.labels}}
          ALLOWED_LABELS: ${{ steps.get-allowed_labels.outputs.LABELS }}