name: 🏷️ Validate PR labels and release notes

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled, edited]

permissions:
  contents: read
  pull-requests: write

jobs:
  pr-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Get allowed PR labels
        id: get-allowed_labels
        env:
          PROJECT_ROOT: ${{ github.workspace }}
        run: |
          FILE_NAME=.pull-requests-allowed-labels-list
          FILE_PATH=$PROJECT_ROOT/$FILE_NAME
          if [[ ! -f "$FILE_PATH" ]]; then
             echo "Error: $FILE_NAME file doesn't exist in the root of the repository"
             exit 1
          fi
          # Add 'chore', 'improvement', 'release' as allowed labels
          echo "LABELS=$(cat $FILE_PATH),chore,improvement,release" >> $GITHUB_OUTPUT

      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.9

      - name: Add release label
        if: startsWith(github.event.pull_request.head.ref, 'release/')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "release"

      - name: Auto-approve release PR
        if: startsWith(github.event.pull_request.head.ref, 'release/')
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate release notes per label
        if: "!startsWith(github.event.pull_request.head.ref, 'release/')"
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
          PR_LABELS: ${{ steps.pr-labels.outputs.labels }}
          ALLOWED_LABELS: ${{ steps.get-allowed_labels.outputs.LABELS }}
        run: |
          IFS=',' read -r -a LABELS_ARRAY <<< "$ALLOWED_LABELS"

          SKIP_LABELS=("chore" "improvement" "release")

          SHOULD_FAIL_JOB="false"
          RED='\033[0;31m'
          NC='\033[0m'

          for LABEL in "${LABELS_ARRAY[@]}"; do
            LABEL=$(echo "$LABEL" | sed 's/^ *//;s/ *$//')
            
            if [[ " ${SKIP_LABELS[*]} " == *" $LABEL "* ]]; then
              continue
            fi

            if [[ "$PR_LABELS" == *"$LABEL"* ]]; then
              NOTE=$(echo "$PR_BODY" | grep -Poz "(?s)<$LABEL>.*?</$LABEL>" || true)
              if [[ -z "$NOTE" ]]; then
                echo -e "${RED}Pull requests labeled with '$LABEL' must have a release note in the PR body formatted as '<$LABEL> {{YOUR NOTE}} </$LABEL>'${NC}"
                SHOULD_FAIL_JOB="true"
              fi
            fi
          done

          if [[ "$SHOULD_FAIL_JOB" == "true" ]]; then
            exit 1
          fi
