name: Build and Test Xcode 12

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Branch to checkout'
        required: true
        default: 'develop'

jobs:
  try_xcode_12:
    runs-on: macos-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        destination: ['name=iPhone 11,OS=14.0']
            
    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'Adyen/adyen-ios'
    
    - name: Set Xcode Version
      run: |
        echo '::set-env name=XCODE_VERSION::/Applications/Xcode_11.4.1.app/Contents/Developer'
        
    - name: Prepare iOS 14.0 simulator
      if: contains(matrix.destination, 'OS=14.0')
      run: |
        sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
        sudo ln -s /Applications/Xcode_12_beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 14.0.simruntime
        xcrun simctl create custom-test-device "iPhone 11" "com.apple.CoreSimulator.SimRuntime.iOS-14-0"
        xcrun simctl list devices 14.0
        
    - name: Check Dependencies
      uses: actions/cache@v1
      id: carthage-cache
      with:
        path: Carthage
        key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
      
    - name: Install Dependencies
      if: steps.carthage-cache.outputs.cache-hit != 'true'
      run: |
        carthage bootstrap --platform iOS --cache-builds
      
    - name: Build and test
      run: |
        xcodebuild -project Adyen.xcodeproj -scheme AdyenUIHost -destination "${destination}" -derivedDataPath ./DerivedData -enableCodeCoverage YES build test | xcpretty
      env:
        destination: ${{ matrix.destination }}
        DEVELOPER_DIR: ${{ env.XCODE_VERSION }}
