name: Build and Test Xcode 12

on:
  workflow_dispatch:

jobs:
  try_xcode_12:
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['name=iPhone 11,OS=14.0']
            
    steps:
    - uses: actions/checkout@v2
    
    - name: Set Xcode Version
      run: |
        echo '::set-env name=XCODE_VERSION::/Applications/Xcode_12_beta.app/Contents/Developer'
        
    - name: Check Dependencies
      uses: actions/cache@v1
      id: carthage-cache
      with:
        path: Carthage
        key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
      
    - name: Install Dependencies
      if: steps.carthage-cache.outputs.cache-hit != 'true'
      run: |
        carthage bootstrap --platform iOS --cache-builds
      
    - name: Build and test
      run: |
        xcodebuild -project Adyen.xcodeproj -scheme AdyenUIHost -destination "${destination}" -derivedDataPath ./DerivedData -enableCodeCoverage YES build test | xcpretty
      env:
        destination: ${{ matrix.destination }}
        DEVELOPER_DIR: ${{ env.XCODE_VERSION }}
